ALTER TABLE login ADD COLUMN IF NOT EXISTS last_heartbeat_at TIMESTAMP;
ALTER TABLE login ADD COLUMN IF NOT EXISTS last_heartbeat_lat DOUBLE PRECISION;
ALTER TABLE login ADD COLUMN IF NOT EXISTS last_heartbeat_lng DOUBLE PRECISION;
