ALTER TABLE checklist_questions
  ADD COLUMN IF NOT EXISTS question_type VARCHAR(20) NOT NULL DEFAULT 'binary',
  ADD COLUMN IF NOT EXISTS options JSONB DEFAULT NULL;

ALTER TABLE checklist_answers
  ADD COLUMN IF NOT EXISTS answer_value VARCHAR(100) DEFAULT NULL;
